### ISSUE TITLE
How would you connect a Member and an ApplicationUser?

### ISSUE THREAD

**Issue by bokerman** [ardalis/DevBetterWeb#102]
Am I correct by assuming that Idenitiy (in UI, Infrastructure and Core project) is being treated as a separate Bounded context? What I'm trying to do is to avoid inheriting ApplicaionUser in the Member type and keep Identity and Member DbContexts separate - similar to DevBetterWeb. The difference is that association of the Member and Application user is optional in DevBetterWeb while i would need to create them at the same time. How would you associate a Member entity with ApplicationUser created by Identity framework? Would you keep Bounded contexts and DbContext separate and raise an event when an Application users created in Identity than handle that event and Create a new Member? Or do it n some transactional manner in a service?

**Comment by bokerman** [comment]
...and many thanks for help Steve. I'm not sure if this is the best way to ask questions here.

**Comment by ardalis** [comment]
Thanks for the sponsorship!

Any of the options you mention sound reasonable to meet your requirement. My first thought is to question the requirement. Why do you need the identity and member classes/constructs/records to be created *at the same time*? Usually auth concerns are separate from member registration concerns, and in fact in many web applications you have a variety of ways in which you can register and authenticate (including with existing accounts at other sites like Facebook, Google, Microsoft, etc.).

If you have to couple them, I think the event approach appeals most to me. Unless you *really* need it I would avoid the transaction requirement. I'd be fine if the identity insert succeeded but the event to create the member failed. I'd report that to the user and/or the system's dev team and resolve the problem from there.

HTH.

**Comment by bokerman** [comment]
Thank you for the answer Steve.
The reason why I would like to create them at the same request it that registration process requires personal, business (type of business) and login (email/username, password) details in the same form. Maybe I don't see something here but my idea is to take login details and create Identity user and after that take userId and pass it to the appropriate event handler that will create a Member (with the rest of the personal/business details) and also associate it with Identity user with userId. 
Maybe there is a better approach here?

**Comment by ardalis** [comment]
Sure, that would work. Though, for something like this where the process is always going to involve creating a certain set of things an even simpler approach might just be to have an application service that does each of the required steps, possibly in a transaction if needed. Either one will work. The event-based approach is more flexible but if you don't need that flexibility it might be overkill here.
