### ISSUE TITLE
Create Production Environment

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevBetterWeb#36]
- [x] Create local databases (LocalDb)
- [x] Deploy and test migrations and seed data with local databases
- [x] Create production Azure SQL database(s)
- [x] Deploy from VS to Azure with Migrations to the new database(s)
- [x] Configure Release pipeline to deploy app to production (without migrations/db)

For now update prod db manually.

**Comment by ardalis** [comment]
How close is this to done?

**Comment by efleming18** [comment]
The only thing left on this is the release pipeline. The new site is deployed, migrations applied, etc.

**Comment by ardalis** [comment]
This should be GitHub Actions.

**Comment by ardalis** [comment]
Confirmed releases are working via Github Actions
