### ISSUE TITLE
Send an email when a user is added to a role

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevBetterWeb#49]
Email the user and all members of the admin role (via bcc or separate to, not CC) whenever they're added to a role.

Don't send emails when a user is removed from a role.

**Comment by Joe-LaRue** [comment]
what SMTP server should be specified for email services?

**Comment by ardalis** [comment]
Use an interface to represent whatever service we'll use. I imagine we can use a free or very inexpensive version of SendGrid for the implementation.

**Comment by ardalis** [comment]
This should be hooked up - testing.

**Comment by ardalis** [comment]
Not done. Let's change this to:

- [ ] Raise an event when a user is added to a role
- [ ] Create an event handler to notify DiscordAdmin that someone was added to a role

**Comment by ardalis** [comment]
Also notify when removed from roles.
