### ISSUE TITLE
Confirm email address

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevBetterWeb#50]
It should be possible to confirm a user's email address by sending them an email and having them click a link or enter a code.

**Comment by Joe-LaRue** [comment]
should this happen on account creation only?  I think email confirmation is built in to identity framework isn't it?

**Comment by ardalis** [comment]
I think so it just needs configured to use whatever email service we set up.

**Comment by Joe-LaRue** [comment]
Created a branch for this and setup some of the plumbing for email confirmation with identity, using the tutorial at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/accconfirm?view=aspnetcore-2.1&tabs=visual-studio

A SendGrid account needs to be setup, so we can configure the user secret and test!

**Comment by Joe-LaRue** [comment]
tested with test API key!  success!
