### ISSUE TITLE
Member Profile Info

### ISSUE THREAD

**Issue by ardalis** [ardalis/DevBetterWeb#53]
Members should be able to (optionally) add to their profile:
LinkedIn URL
Twitter URL
GitHub URL
Blog URL
Twitch.TV URL
[other] URL

**Comment by Joe-LaRue** [comment]
Should a user profile have a fixed list of URLs, or a more generic collection of key/values (name, URL)?  We can either add individual fields to the user table for each one (TwitterUrl, GithubUrl, etc) or create something like a UserLinks table with a Name and a URL field.  

Maybe when people add a URL, they can either put in their own name, or pick from a canned list (containing common ones like twitter, GitHub, etc)

Also, maybe the names come from a different UrlType table, and have an image/icon associated with them?  Just spit-balling here!

**Comment by Joe-LaRue** [comment]
created a new branch for this.  I have added some properties to the ASP.NET Identity user - the URLs listed in this issue, plus first name, last name, address, and about.  There are migrations that need to be applied to the database (see efScripts.txt for the identity migration command).

I created a MyProfile page, where a user can edit their details, a Members page, where users can see a list of other members and, and a details page, that will display a user's basic public details (links, first/last name,  and about)

Links are validated on the MyProfile pages via custom attribute.

**Comment by ardalis** [comment]
My preference is to put the profile info into a separate entity, like Subscriber or Member or something. It will have a 1:1 relationship with the built-in user type, but by keeping the user record tiny (not adding to it) it makes it easier to shift auth systems later if required (I've been bitten by this enough times...).

**Comment by Joe-LaRue** [comment]
The branch has been updated!  created members entity and moved all properties over to there, out of the identity table

**Comment by ardalis** [comment]
I made some adjustments. Using separate config files now. Turned Member into a BaseEntity (so ID key not UserId). Added a CreatedDate. That's about it. You can add some UI to it now if you like, or just PR it as-is if you think you're not going to have time to do more soon.

**Comment by Joe-LaRue** [comment]
Cool :)  Were you able to apply the new migration that changes the key for Member?  I'm getting this error: ```To change the IDENTITY property of a column, the column needs to be dropped and recreated.```

**Comment by Joe-LaRue** [comment]
There was a problem with the migration that I had to fix.  The migration you added was trying to undo things from my initial migration, and exploding.  I deleted both migrations and created a new one, which worked in my test environment!  going to submit this PR

**Comment by ardalis** [comment]
Cool

**Comment by ardalis** [comment]
This issue is complete.
