### ISSUE TITLE
Email verification is sent when invalid password is used

### ISSUE THREAD

**Issue by Joe-LaRue** [ardalis/DevBetterWeb#66]
only send email verification is password sign in was successful

**Comment by ardalis** [comment]
Per this article maybe we don't want to send verifications from the login POST:
https://code-maze.com/email-confirmation-aspnet-core-identity/#modifying_login_action

**Comment by ardalis** [comment]
I think this is working correctly. It should only send the confirmation email if the user signs in successfully but `!user.EmailConfirmed`
